
[entryPoints]
    [entryPoints.http]
    address = ":80"


[providers]
  [providers.file]
    directory = "."
    watch = true
#    filename = "traefik.toml"


[accessLog]

[log]
  level = "INFO"

[http]
   [http.routers.to-whoami-service]
      rule = "Host(`test.localhost`) || Host(`test2.localhost`)"
      service = "whoami"
      middlewares = ["modify-hostname"]
    [http.routers.to-service-2]
      rule = "Host(`test1.localhost`)"
      service = "whoami"

[http.middlewares]
  [http.middlewares.modify-hostname.headers.customRequestHeaders]
    Host = "service.external"

[http.services]
  [http.services.whoami.loadBalancer]
    [[http.services.whoami.loadBalancer.servers]]
      url = "http://localhost:8081"